(()=>{'use strict';
const $=id=>document.getElementById(id),STORE='yard_shapes_v13';
let map,pos=null,follow=true,programmatic=false,editing=false,boundariesOn=true,satelliteOn=false;
let draftPts=[],draftClosed=false,draftLayers=[],preview=null,previewLabel=null;
let drawMode=null,drawPts=[],drawLayers=[],savedLayers=[],editMarkers=[],activeId=null,pending=null;
let gpsMarker=null,accCircle=null,cad=null,base=null,ortho=null,satellite=null;
const rad=x=>x*Math.PI/180;
function dist(a,b){const R=6371008.8,d1=rad(b.lat-a.lat),d2=rad(b.lng-a.lng),h=Math.sin(d1/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(d2/2)**2;return 2*R*Math.asin(Math.sqrt(Math.min(1,h)))}
function mid(a,b){return[(a.lat+b.lat)/2,(a.lng+b.lng)/2]}
function center(p){return{lat:p.reduce((s,x)=>s+x.lat,0)/p.length,lng:p.reduce((s,x)=>s+x.lng,0)/p.length}}
function area(p){if(p.length<3)return 0;const R=6371008.8,m=rad(p.reduce((s,x)=>s+x.lat,0)/p.length),q=p.map(x=>[R*rad(x.lng)*Math.cos(m),R*rad(x.lat)]);let s=0;for(let i=0;i<q.length;i++){const a=q[i],b=q[(i+1)%q.length];s+=a[0]*b[1]-b[0]*a[1]}return Math.abs(s)/2}
function length(p,close=false){let s=0;for(let i=1;i<p.length;i++)s+=dist(p[i-1],p[i]);if(close&&p.length>2)s+=dist(p.at(-1),p[0]);return s}
function fmt(m){const c=Math.max(0,Math.round(m*100));return[(c/100).toFixed(2)+' m',Math.floor(c/100)+' m '+c%100+' cm']}
function icon(cls){return L.divIcon({className:'',html:`<div class="${cls}"></div>`,iconSize:[20,20],iconAnchor:[10,10]})}
function moveIcon(){return L.divIcon({className:'',html:'<div style="width:34px;height:34px;border-radius:50%;border:3px solid #fff;background:#00a884;color:#fff;display:flex;align-items:center;justify-content:center;font-size:18px;font-weight:900;box-shadow:0 3px 12px #0009">✥</div>',iconSize:[34,34],iconAnchor:[17,17]})}
function textIcon(t,small=false){return L.divIcon({className:'measure-icon',html:`<div class="measure-text${small?' saved':''}">${t}</div>`,iconSize:[1,1],iconAnchor:[0,0]})}
function clear(arr){arr.forEach(x=>{try{map.removeLayer(x)}catch(_){}});arr.length=0}
function getAll(){try{const a=JSON.parse(localStorage.getItem(STORE)||'[]');return Array.isArray(a)?a:[]}catch(_){return[]}}
function putAll(a){localStorage.setItem(STORE,JSON.stringify(a));window.dispatchEvent(new Event('yard-data-changed'))}
function normalize(s){return{...s,id:Number(s.id)||Date.now(),name:s.name||'Objekts',type:s.type==='line'?'line':'area',color:s.color||'#ff4b2b',height:Math.max(0,Number(s.height)||0),points:Array.isArray(s.points)?s.points.map(p=>({lat:+p.lat,lng:+p.lng})).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lng)):[]}}
function toast(t){const el=$('toast');el.textContent=t;el.classList.add('show');clearTimeout(window.__yt);window.__yt=setTimeout(()=>el.classList.remove('show'),1600)}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function pointInPolygon(ll,pts){let inside=false;for(let i=0,j=pts.length-1;i<pts.length;j=i++){const xi=pts[i].lng,yi=pts[i].lat,xj=pts[j].lng,yj=pts[j].lat;const cross=((yi>ll.lat)!=(yj>ll.lat))&&(ll.lng<(xj-xi)*(ll.lat-yi)/((yj-yi)||1e-12)+xi);if(cross)inside=!inside}return inside}
function pxSegDistance(click,a,b){const p=map.latLngToContainerPoint(click),A=map.latLngToContainerPoint([a.lat,a.lng]),B=map.latLngToContainerPoint([b.lat,b.lng]);const vx=B.x-A.x,vy=B.y-A.y,wx=p.x-A.x,wy=p.y-A.y,den=vx*vx+vy*vy;const t=den?Math.max(0,Math.min(1,(wx*vx+wy*vy)/den)):0;const x=A.x+t*vx,y=A.y+t*vy;return Math.hypot(p.x-x,p.y-y)}
function shapePixelDistance(ll,s){if(s.type==='area'&&pointInPolygon(ll,s.points))return 0;let best=Infinity,count=s.type==='line'?s.points.length-1:s.points.length;for(let i=0;i<count;i++){const d=pxSegDistance(ll,s.points[i],s.points[(i+1)%s.points.length]);if(d<best)best=d}return best}
function findShapeAt(ll){const all=getAll().map(normalize).filter(s=>s.points.length>=(s.type==='line'?2:3));let best=null,bestD=Infinity;for(let i=all.length-1;i>=0;i--){const d=shapePixelDistance(ll,all[i]);if(d<bestD){bestD=d;best=all[i]}if(d===0)break}return bestD<=42?best:null}
function savePoint(id,index,ll){const a=getAll(),o=a.find(x=>Number(x.id)===id);if(!o)return;o.points[index]={lat:ll.lat,lng:ll.lng};putAll(a)}
function moveShape(id,from,to){const a=getAll(),o=a.find(x=>Number(x.id)===id);if(!o)return;const dLat=to.lat-from.lat,dLng=to.lng-from.lng;o.points=o.points.map(p=>({lat:+p.lat+dLat,lng:+p.lng+dLng}));putAll(a)}
function showSelectionMenu(s,ll){L.popup({closeButton:true,autoPan:false}).setLatLng(ll).setContent(`<div style="min-width:155px"><b>${esc(s.name)}</b><div style="font-size:12px;margin:5px 0;color:#555">${s.type==='area'?area(s.points).toFixed(2)+' m² · ':''}${length(s.points,s.type==='area').toFixed(2)} m</div><button onclick="YARD_PARAMS()" style="width:100%;padding:8px;margin-top:4px;border:0;border-radius:8px;background:#27303a;color:#fff">Parametri</button><button onclick="YARD_DELETE()" style="width:100%;padding:8px;margin-top:6px;border:0;border-radius:8px;background:#7b1f27;color:#fff">Dzēst</button></div>`).openOn(map)}
function renderSaved(){clear(savedLayers);clear(editMarkers);const all=getAll().map(normalize);all.forEach(s=>{if(s.points.length<(s.type==='line'?2:3))return;const coords=s.points.map(p=>[p.lat,p.lng]),color=s.color;const visible=s.type==='line'?L.polyline(coords,{pane:'saved',color,weight:activeId===s.id&&editing?6:4,interactive:false}):L.polygon(coords,{pane:'saved',color,weight:activeId===s.id&&editing?5:3,fillColor:color,fillOpacity:activeId===s.id&&editing?.32:.22,interactive:false});visible.addTo(map);savedLayers.push(visible);const count=s.type==='line'?s.points.length-1:s.points.length;for(let i=0;i<count;i++){const a=s.points[i],b=s.points[(i+1)%s.points.length];savedLayers.push(L.marker(mid(a,b),{pane:'saved',icon:textIcon(fmt(dist(a,b))[0],true),interactive:false}).addTo(map))}
 if(editing&&activeId===s.id){s.points.forEach((p,i)=>{const m=L.marker([p.lat,p.lng],{pane:'measure',icon:icon('edit-pt'),draggable:true,zIndexOffset:1600}).addTo(map);m.on('dragend',e=>{savePoint(s.id,i,e.target.getLatLng());renderSaved();const u=getAll().map(normalize).find(x=>x.id===s.id);if(u)showSelectionMenu(u,e.target.getLatLng())});editMarkers.push(m)});const c=center(s.points);const mover=L.marker([c.lat,c.lng],{pane:'measure',icon:moveIcon(),draggable:true,zIndexOffset:1700}).addTo(map);mover.on('dragstart',()=>map.closePopup());mover.on('dragend',e=>{moveShape(s.id,c,e.target.getLatLng());renderSaved();const u=getAll().map(normalize).find(x=>x.id===s.id);if(u)showSelectionMenu(u,e.target.getLatLng())});editMarkers.push(mover)}
 })}
function selectShape(s,ll){activeId=s.id;renderSaved();showSelectionMenu(s,ll);$('title').textContent='Objekts atlasīts';$('sub').textContent='Velc zaļos punktus vai ✥, lai pārvietotu visu objektu'}
function openEditor(obj,isNew){pending={...normalize(obj),isNew};$('modalTitle').textContent=isNew?'Saglabāt objektu':'Rediģēt objektu';$('name').value=pending.name||'';$('shapeColor').value=pending.color;$('height').value=pending.type==='area'?pending.height:0;$('heightField').style.display=pending.type==='area'?'block':'none';$('area').textContent=pending.type==='area'?area(pending.points).toFixed(2)+' m²':'—';$('per').textContent=length(pending.points,pending.type==='area').toFixed(2)+' m';$('deleteObject').style.display=isNew?'none':'block';$('modal').classList.add('show')}
function saveEditor(){if(!pending)return;const wasNew=!!pending.isNew,all=getAll(),obj=normalize({...pending,name:$('name').value.trim()||pending.name||'Objekts',color:$('shapeColor').value,height:pending.type==='area'?Math.max(0,+$('height').value||0):0});delete obj.isNew;const i=all.findIndex(x=>Number(x.id)===obj.id);if(i>=0)all[i]=obj;else all.push(obj);putAll(all);if(wasNew){draftPts=[];draftClosed=false;clear(draftLayers);clearPreview();drawMode=null;drawPts=[];clear(drawLayers);$('drawLine').classList.remove('active');$('drawArea').classList.remove('active')}activeId=obj.id;pending=null;$('modal').classList.remove('show');renderSaved();ui();toast('Saglabāts')}
function deleteId(id){if(id==null)return;if(!confirm('Dzēst šo objektu?'))return;putAll(getAll().filter(x=>Number(x.id)!==Number(id)));pending=null;activeId=null;$('modal').classList.remove('show');map.closePopup();renderSaved();ui();toast('Objekts dzēsts')}
function deleteActive(){if(pending&&!pending.isNew)deleteId(pending.id)}
window.YARD_PARAMS=()=>{if(activeId==null)return;const s=getAll().map(normalize).find(x=>x.id===activeId);if(s){map.closePopup();openEditor(s,false)}};
window.YARD_DELETE=()=>deleteId(activeId);
function clearPreview(){if(preview)map.removeLayer(preview);if(previewLabel)map.removeLayer(previewLabel);preview=previewLabel=null;$('live').textContent='0.00 m';$('livecm').textContent='0 m 0 cm'}
function renderDraft(){clear(draftLayers);clearPreview();for(let i=1;i<draftPts.length;i++){const a=draftPts[i-1],b=draftPts[i];draftLayers.push(L.polyline([[a.lat,a.lng],[b.lat,b.lng]],{pane:'measure',color:'#ff4b2b',weight:5}).addTo(map));draftLayers.push(L.marker(mid(a,b),{pane:'measure',icon:textIcon(fmt(dist(a,b))[0]),interactive:false}).addTo(map))}if(draftClosed&&draftPts.length>2)draftLayers.push(L.polygon(draftPts.map(p=>[p.lat,p.lng]),{pane:'measure',color:'#ff4b2b',fillOpacity:.08}).addTo(map));draftPts.forEach((p,i)=>{const m=L.marker([p.lat,p.lng],{pane:'measure',icon:icon('pt'),draggable:editing}).addTo(map);if(editing)m.on('dragend',e=>{const ll=e.target.getLatLng();draftPts[i]={lat:ll.lat,lng:ll.lng};renderDraft()});draftLayers.push(m)});updatePreview();ui()}
function updatePreview(){if(!pos||!draftPts.length||draftClosed)return;clearPreview();const a=draftPts.at(-1),d=dist(a,pos);preview=L.polyline([[a.lat,a.lng],[pos.lat,pos.lng]],{pane:'measure',color:'#ff9f1c',weight:4,dashArray:'8 7'}).addTo(map);previewLabel=L.marker(mid(a,pos),{pane:'measure',icon:textIcon(fmt(d)[0]),interactive:false}).addTo(map);$('live').textContent=fmt(d)[0];$('livecm').textContent=fmt(d)[1]}
function ui(){const active=draftPts.length&&!draftClosed;$('main').disabled=!pos;$('main').textContent=!draftPts.length?'Uzlikt sākuma punktu':active?'Fiksēt punktu':'Jauns mērījums';$('undo').disabled=!draftPts.length;$('finish').disabled=draftPts.length<2||draftClosed;$('close').disabled=draftPts.length<3||draftClosed;if(!pos){$('title').textContent='GPS inicializācija';return}if(!draftPts.length){$('title').textContent=editing?'Rediģēšanas režīms':'GPS gatavs';$('sub').textContent=editing?(activeId?'Velc punktus vai ✥, lai pārvietotu objektu':'Pieskaries jebkuram saglabātam objektam'):'Nostājies stūrī un fiksē sākuma punktu'}else{$('title').textContent='Mērīšana aktīva';$('sub').textContent='Ej uz nākamo punktu — līnija seko GPS'}}
function startDraw(type){if(drawMode===type){finishDraw();return}drawMode=type;drawPts=[];clear(drawLayers);follow=false;$('follow').classList.remove('active');$('drawLine').classList.toggle('active',type==='line');$('drawArea').classList.toggle('active',type==='area');toast('Pieskaries punktiem. Nospied to pašu pogu vēlreiz, lai pabeigtu.')}
function renderDraw(){clear(drawLayers);if(!drawPts.length)return;const c=drawPts.map(p=>[p.lat,p.lng]);const l=drawMode==='area'&&drawPts.length>=3?L.polygon(c,{pane:'measure',color:'#ff9f1c',weight:3,fillOpacity:.12}):L.polyline(c,{pane:'measure',color:'#ff9f1c',weight:4,dashArray:'7 6'});drawLayers.push(l.addTo(map));drawPts.forEach(p=>drawLayers.push(L.marker([p.lat,p.lng],{pane:'measure',icon:icon('draw-pt'),interactive:false}).addTo(map)))}
function finishDraw(){if(!drawMode)return;const min=drawMode==='line'?2:3;if(drawPts.length<min){toast(`Vajag vismaz ${min} punktus`);return}const obj={id:Date.now(),name:drawMode==='line'?'Līnija':'Laukums',type:drawMode,color:'#ff4b2b',height:0,points:drawPts.map(p=>({...p}))};drawMode=null;drawPts=[];clear(drawLayers);$('drawLine').classList.remove('active');$('drawArea').classList.remove('active');openEditor(obj,true)}
function setSatellite(on){satelliteOn=!!on;$('satellite').classList.toggle('active',satelliteOn);if(satelliteOn){if(ortho&&map.hasLayer(ortho))map.removeLayer(ortho);if(satellite&&!map.hasLayer(satellite))satellite.addTo(map);satellite.bringToBack();if(base&&map.hasLayer(base))base.bringToBack();toast('Satelīta skats')}else{if(satellite&&map.hasLayer(satellite))map.removeLayer(satellite);if(ortho&&!map.hasLayer(ortho))ortho.addTo(map);ortho.bringToFront();toast('Ortofoto skats')}if(boundariesOn&&cad&&map.hasLayer(cad)){cad.bringToFront();cad.redraw()}renderSaved()}
function init(){map=L.map('map',{zoomControl:false,preferCanvas:true,doubleClickZoom:false}).setView([56.9496,24.1052],18);map.createPane('ortho');map.getPane('ortho').style.zIndex=220;map.createPane('satellite');map.getPane('satellite').style.zIndex=230;map.createPane('cad');map.getPane('cad').style.zIndex=360;map.createPane('saved');map.getPane('saved').style.zIndex=520;map.createPane('measure');map.getPane('measure').style.zIndex=620;
 base=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:21,maxNativeZoom:19,attribution:'© OpenStreetMap'}).addTo(map);
 ortho=L.tileLayer.wms('https://lvmgeoserver.lvm.lv/geoserver/ows',{pane:'ortho',layers:'public:Orto_LKS',styles:'',format:'image/vnd.jpeg-png8',transparent:false,version:'1.3.0',crs:L.CRS.EPSG3857,maxZoom:22,uppercase:true,attribution:'Ortofoto © LĢIA / LVM GEO'}).addTo(map);
 satellite=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{pane:'satellite',maxZoom:20,maxNativeZoom:20,attribution:'Tiles © Esri — Source: Esri, Maxar, Earthstar Geographics, and the GIS User Community'});
 cad=L.tileLayer.wms('https://lvmgeoserver.lvm.lv/geoserver/ows',{pane:'cad',layers:'publicwfs:Kadastra_karte',styles:'',format:'image/png',transparent:true,version:'1.3.0',crs:L.CRS.EPSG3857,minZoom:9,maxZoom:22,uppercase:true,opacity:1,interactive:false,updateWhenIdle:false,keepBuffer:4,attribution:'Kadastra dati © VZD / LVM GEO'}).addTo(map);
 cad.on('tileerror',()=>{clearTimeout(window.__cadRetry);window.__cadRetry=setTimeout(()=>{if(boundariesOn&&map.hasLayer(cad))cad.redraw()},1200)});
 renderSaved();ui();
 $('main').onclick=()=>{if(!pos)return;if(!draftPts.length||draftClosed){draftPts=[];draftClosed=false}draftPts.push({lat:pos.lat,lng:pos.lng});renderDraft()};$('undo').onclick=()=>{draftPts.pop();renderDraft()};$('finish').onclick=()=>{if(draftPts.length>=2)openEditor({id:Date.now(),name:'Līnija',type:'line',color:'#ff4b2b',height:0,points:draftPts.map(p=>({...p}))},true)};$('close').onclick=()=>{if(draftPts.length>=3){draftClosed=true;renderDraft();openEditor({id:Date.now(),name:'Laukums',type:'area',color:'#ff4b2b',height:0,points:draftPts.map(p=>({...p}))},true)}};$('reset').onclick=()=>{draftPts=[];draftClosed=false;clear(draftLayers);clearPreview();ui()};
 $('drawLine').onclick=()=>startDraw('line');$('drawArea').onclick=()=>startDraw('area');$('models').onclick=()=>location.href='yard-3d.html?v=18';$('satellite').onclick=()=>setSatellite(!satelliteOn);$('edit').onclick=()=>{editing=!editing;activeId=null;map.closePopup();$('edit').classList.toggle('active',editing);renderSaved();renderDraft();ui();toast(editing?'✎ Pieskaries jebkuram objektam':'Rediģēšana izslēgta')};$('save').onclick=saveEditor;$('cancel').onclick=()=>{$('modal').classList.remove('show');pending=null};$('deleteObject').onclick=deleteActive;$('pdf').onclick=()=>window.print();
 $('panelToggle').onclick=()=>{const h=$('bottom').classList.toggle('hidden');$('panelToggle').classList.toggle('panel-open',!h);$('panelToggle').textContent=h?'⌃':'⌄';setTimeout(()=>map.invalidateSize(),220)};$('follow').onclick=()=>{follow=true;$('follow').classList.add('active');if(pos){programmatic=true;map.setView([pos.lat,pos.lng],Math.max(19,map.getZoom()),{animate:false});setTimeout(()=>programmatic=false,100)}};$('boundaries').onclick=()=>{boundariesOn=!boundariesOn;$('boundaries').classList.toggle('active',boundariesOn);if(boundariesOn){cad.addTo(map);cad.bringToFront();cad.redraw()}else map.removeLayer(cad)};
 map.on('dragstart zoomstart',()=>{if(programmatic||drawMode)return;follow=false;$('follow').classList.remove('active')});map.on('click',e=>{if(drawMode){drawPts.push({lat:e.latlng.lat,lng:e.latlng.lng});renderDraw();return}if(editing){const s=findShapeAt(e.latlng);if(s){selectShape(s,e.latlng)}else{activeId=null;map.closePopup();renderSaved();ui();toast('Šeit nav atlasāma objekta')}}});map.on('moveend zoomend',()=>{if(boundariesOn&&cad&&map.hasLayer(cad))cad.redraw()});
 if(navigator.geolocation)navigator.geolocation.watchPosition(p=>{pos={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy};$('gpsText').textContent='± '+Math.round(pos.accuracy)+' m';$('dot').className='dot '+(pos.accuracy<=5?'good':pos.accuracy>15?'bad':'');const ll=[pos.lat,pos.lng];if(!gpsMarker)gpsMarker=L.marker(ll,{pane:'measure',icon:icon('gps'),interactive:false,zIndexOffset:1800}).addTo(map);else gpsMarker.setLatLng(ll);if(!accCircle)accCircle=L.circle(ll,{pane:'measure',radius:pos.accuracy,color:'#2f80ff',weight:2,fillColor:'#2f80ff',fillOpacity:.08,interactive:false}).addTo(map);else accCircle.setLatLng(ll).setRadius(pos.accuracy);if(follow){programmatic=true;map.setView(ll,Math.max(19,map.getZoom()),{animate:false});setTimeout(()=>programmatic=false,100)}updatePreview();ui()},e=>{$('dot').className='dot bad';$('gpsText').textContent=e.code===1?'GPS bloķēts':'GPS kļūda'},{enableHighAccuracy:true,maximumAge:0,timeout:20000});
 window.addEventListener('storage',renderSaved);window.addEventListener('yard-data-changed',renderSaved);setTimeout(()=>{map.invalidateSize();if(cad)cad.redraw()},250)}
init();
})();