(()=>{'use strict';
const $=id=>document.getElementById(id),STORE='yard_shapes_v13';
let map,pos=null,follow=true,programmatic=false,editing=false,boundariesOn=true;
let draftPts=[],draftClosed=false,draftLayers=[],preview=null,previewLabel=null;
let drawMode=null,drawPts=[],drawLayers=[],savedLayers=[],editMarkers=[],activeId=null,pending=null;
let gpsMarker=null,accCircle=null,cad=null;
const rad=x=>x*Math.PI/180;
function dist(a,b){const R=6371008.8,d1=rad(b.lat-a.lat),d2=rad(b.lng-a.lng),h=Math.sin(d1/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(d2/2)**2;return 2*R*Math.asin(Math.sqrt(Math.min(1,h)))}
function mid(a,b){return[(a.lat+b.lat)/2,(a.lng+b.lng)/2]}
function area(p){if(p.length<3)return 0;const R=6371008.8,m=rad(p.reduce((s,x)=>s+x.lat,0)/p.length),q=p.map(x=>[R*rad(x.lng)*Math.cos(m),R*rad(x.lat)]);let s=0;for(let i=0;i<q.length;i++){const a=q[i],b=q[(i+1)%q.length];s+=a[0]*b[1]-b[0]*a[1]}return Math.abs(s)/2}
function length(p,close=false){let s=0;for(let i=1;i<p.length;i++)s+=dist(p[i-1],p[i]);if(close&&p.length>2)s+=dist(p.at(-1),p[0]);return s}
function fmt(m){const c=Math.max(0,Math.round(m*100));return[(c/100).toFixed(2)+' m',Math.floor(c/100)+' m '+c%100+' cm']}
function icon(cls){return L.divIcon({className:'',html:`<div class="${cls}"></div>`,iconSize:[20,20],iconAnchor:[10,10]})}
function textIcon(t,small=false){return L.divIcon({className:'measure-icon',html:`<div class="measure-text${small?' saved':''}">${t}</div>`,iconSize:[1,1],iconAnchor:[0,0]})}
function clear(arr){arr.forEach(x=>{try{map.removeLayer(x)}catch(_){}});arr.length=0}
function getAll(){try{const a=JSON.parse(localStorage.getItem(STORE)||'[]');return Array.isArray(a)?a:[]}catch(_){return[]}}
function putAll(a){localStorage.setItem(STORE,JSON.stringify(a));window.dispatchEvent(new Event('yard-data-changed'))}
function toast(t){const el=$('toast');el.textContent=t;el.classList.add('show');clearTimeout(window.__yt);window.__yt=setTimeout(()=>el.classList.remove('show'),1600)}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function normalize(s){return{...s,id:Number(s.id)||Date.now(),name:s.name||'Objekts',type:s.type==='line'?'line':'area',color:s.color||'#ff4b2b',height:Math.max(0,Number(s.height)||0),points:Array.isArray(s.points)?s.points.map(p=>({lat:+p.lat,lng:+p.lng})).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lng)):[]}}
function renderSaved(){clear(savedLayers);clear(editMarkers);getAll().map(normalize).forEach(s=>{if(s.points.length<(s.type==='line'?2:3))return;const coords=s.points.map(p=>[p.lat,p.lng]),color=s.color;let visible,hit;
 if(s.type==='line'){visible=L.polyline(coords,{pane:'saved',color,weight:4,interactive:false}).addTo(map);hit=L.polyline(coords,{pane:'saved',color:'#000',weight:28,opacity:.001,interactive:true}).addTo(map)}
 else{visible=L.polygon(coords,{pane:'saved',color,weight:3,fillColor:color,fillOpacity:.22,interactive:false}).addTo(map);hit=L.polygon(coords,{pane:'saved',color:'#000',weight:16,opacity:.001,fillColor:'#000',fillOpacity:.001,interactive:true}).addTo(map)}
 savedLayers.push(visible,hit);const count=s.type==='line'?s.points.length-1:s.points.length;for(let i=0;i<count;i++){const a=s.points[i],b=s.points[(i+1)%s.points.length];savedLayers.push(L.marker(mid(a,b),{pane:'saved',icon:textIcon(fmt(dist(a,b))[0],true),interactive:false}).addTo(map))}
 hit.on('click',ev=>{L.DomEvent.stopPropagation(ev);activeId=s.id;if(editing){openEditor(s,false);renderSaved()}else{const at=s.points[Math.floor(s.points.length/2)];L.popup().setLatLng([at.lat,at.lng]).setContent(`<b>${esc(s.name)}</b><br>${s.type==='area'?area(s.points).toFixed(2)+' m²<br>':''}${s.height>0?'Augstums: '+s.height.toFixed(1)+' m<br>':''}<span style="font-size:12px">Ieslēdz ✎, lai rediģētu</span>`).openOn(map)}});
 if(editing&&activeId===s.id)s.points.forEach((p,i)=>{const m=L.marker([p.lat,p.lng],{pane:'measure',icon:icon('edit-pt'),draggable:true,zIndexOffset:1500}).addTo(map);m.on('dragend',e=>{const a=getAll(),o=a.find(x=>Number(x.id)===s.id);if(!o)return;const ll=e.target.getLatLng();o.points[i]={lat:ll.lat,lng:ll.lng};putAll(a);const updated=getAll().map(normalize).find(x=>x.id===s.id);renderSaved();if(updated)openEditor(updated,false)});editMarkers.push(m)})
 })}
function openEditor(obj,isNew){pending={...normalize(obj),isNew};$('modalTitle').textContent=isNew?'Saglabāt objektu':'Rediģēt objektu';$('name').value=pending.name||'';$('shapeColor').value=pending.color;$('height').value=pending.type==='area'?pending.height:0;$('heightField').style.display=pending.type==='area'?'block':'none';$('area').textContent=pending.type==='area'?area(pending.points).toFixed(2)+' m²':'—';$('per').textContent=length(pending.points,pending.type==='area').toFixed(2)+' m';$('deleteObject').style.display=isNew?'none':'block';$('modal').classList.add('show')}
function saveEditor(){if(!pending)return;const wasNew=!!pending.isNew,all=getAll(),obj=normalize({...pending,name:$('name').value.trim()||pending.name||'Objekts',color:$('shapeColor').value,height:pending.type==='area'?Math.max(0,+$('height').value||0):0});delete obj.isNew;const i=all.findIndex(x=>Number(x.id)===obj.id);if(i>=0)all[i]=obj;else all.push(obj);putAll(all);if(wasNew){draftPts=[];draftClosed=false;clear(draftLayers);clearPreview();drawMode=null;drawPts=[];clear(drawLayers);$('drawLine').classList.remove('active');$('drawArea').classList.remove('active')}activeId=obj.id;pending=null;$('modal').classList.remove('show');renderSaved();ui();toast('Saglabāts')}
function deleteActive(){if(!pending||pending.isNew)return;const id=pending.id;if(!confirm('Dzēst šo objektu?'))return;putAll(getAll().filter(x=>Number(x.id)!==id));pending=null;activeId=null;$('modal').classList.remove('show');renderSaved();toast('Objekts dzēsts')}
function clearPreview(){if(preview)map.removeLayer(preview);if(previewLabel)map.removeLayer(previewLabel);preview=previewLabel=null;$('live').textContent='0.00 m';$('livecm').textContent='0 m 0 cm'}
function renderDraft(){clear(draftLayers);clearPreview();for(let i=1;i<draftPts.length;i++){const a=draftPts[i-1],b=draftPts[i];draftLayers.push(L.polyline([[a.lat,a.lng],[b.lat,b.lng]],{pane:'measure',color:'#ff4b2b',weight:5}).addTo(map));draftLayers.push(L.marker(mid(a,b),{pane:'measure',icon:textIcon(fmt(dist(a,b))[0]),interactive:false}).addTo(map))}if(draftClosed&&draftPts.length>2)draftLayers.push(L.polygon(draftPts.map(p=>[p.lat,p.lng]),{pane:'measure',color:'#ff4b2b',fillOpacity:.08}).addTo(map));draftPts.forEach((p,i)=>{const m=L.marker([p.lat,p.lng],{pane:'measure',icon:icon('pt'),draggable:editing}).addTo(map);if(editing)m.on('dragend',e=>{const ll=e.target.getLatLng();draftPts[i]={lat:ll.lat,lng:ll.lng};renderDraft()});draftLayers.push(m)});updatePreview();ui()}
function updatePreview(){if(!pos||!draftPts.length||draftClosed)return;clearPreview();const a=draftPts.at(-1),d=dist(a,pos);preview=L.polyline([[a.lat,a.lng],[pos.lat,pos.lng]],{pane:'measure',color:'#ff9f1c',weight:4,dashArray:'8 7'}).addTo(map);previewLabel=L.marker(mid(a,pos),{pane:'measure',icon:textIcon(fmt(d)[0]),interactive:false}).addTo(map);$('live').textContent=fmt(d)[0];$('livecm').textContent=fmt(d)[1]}
function ui(){const active=draftPts.length&&!draftClosed;$('main').disabled=!pos;$('main').textContent=!draftPts.length?'Uzlikt sākuma punktu':active?'Fiksēt punktu':'Jauns mērījums';$('undo').disabled=!draftPts.length;$('finish').disabled=draftPts.length<2||draftClosed;$('close').disabled=draftPts.length<3||draftClosed;if(!pos){$('title').textContent='GPS inicializācija';return}if(!draftPts.length){$('title').textContent=editing?'Rediģēšanas režīms':'GPS gatavs';$('sub').textContent=editing?'Pieskaries jebkuram saglabātam objektam':'Nostājies stūrī un fiksē sākuma punktu'}else{$('title').textContent='Mērīšana aktīva';$('sub').textContent='Ej uz nākamo punktu — līnija seko GPS'}}
function startDraw(type){if(drawMode===type){finishDraw();return}drawMode=type;drawPts=[];clear(drawLayers);follow=false;$('follow').classList.remove('active');$('drawLine').classList.toggle('active',type==='line');$('drawArea').classList.toggle('active',type==='area');toast('Pieskaries punktiem. Nospied to pašu pogu vēlreiz, lai pabeigtu.')}
function renderDraw(){clear(drawLayers);if(!drawPts.length)return;const c=drawPts.map(p=>[p.lat,p.lng]);const l=drawMode==='area'&&drawPts.length>=3?L.polygon(c,{pane:'measure',color:'#ff9f1c',weight:3,fillOpacity:.12}):L.polyline(c,{pane:'measure',color:'#ff9f1c',weight:4,dashArray:'7 6'});drawLayers.push(l.addTo(map));drawPts.forEach(p=>drawLayers.push(L.marker([p.lat,p.lng],{pane:'measure',icon:icon('draw-pt'),interactive:false}).addTo(map)))}
function finishDraw(){if(!drawMode)return;const min=drawMode==='line'?2:3;if(drawPts.length<min){toast(`Vajag vismaz ${min} punktus`);return}const obj={id:Date.now(),name:drawMode==='line'?'Līnija':'Laukums',type:drawMode,color:'#ff4b2b',height:0,points:drawPts.map(p=>({...p}))};drawMode=null;drawPts=[];clear(drawLayers);$('drawLine').classList.remove('active');$('drawArea').classList.remove('active');openEditor(obj,true)}
function init(){map=L.map('map',{zoomControl:false,preferCanvas:true,doubleClickZoom:false}).setView([56.9496,24.1052],18);map.createPane('ortho');map.getPane('ortho').style.zIndex=220;map.createPane('cad');map.getPane('cad').style.zIndex=360;map.createPane('saved');map.getPane('saved').style.zIndex=520;map.createPane('measure');map.getPane('measure').style.zIndex=620;
 L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:21,maxNativeZoom:19,attribution:'© OpenStreetMap'}).addTo(map);
 L.tileLayer.wms('https://lvmgeoserver.lvm.lv/geoserver/ows',{pane:'ortho',layers:'public:Orto_LKS',styles:'',format:'image/vnd.jpeg-png8',transparent:false,version:'1.3.0',crs:L.CRS.EPSG3857,maxZoom:22,uppercase:true,attribution:'Ortofoto © LĢIA / LVM GEO'}).addTo(map);
 cad=L.tileLayer.wms('https://lvmgeoserver.lvm.lv/geoserver/ows',{pane:'cad',layers:'publicwfs:Kadastra_karte',styles:'',format:'image/png',transparent:true,version:'1.3.0',crs:L.CRS.EPSG3857,minZoom:9,maxZoom:22,uppercase:true,opacity:1,updateWhenIdle:false,keepBuffer:4,attribution:'Kadastra dati © VZD / LVM GEO'}).addTo(map);
 cad.on('tileerror',()=>{clearTimeout(window.__cadRetry);window.__cadRetry=setTimeout(()=>{if(boundariesOn&&map.hasLayer(cad))cad.redraw()},1200)});
 renderSaved();ui();
 $('main').onclick=()=>{if(!pos)return;if(!draftPts.length||draftClosed){draftPts=[];draftClosed=false}draftPts.push({lat:pos.lat,lng:pos.lng});renderDraft()};$('undo').onclick=()=>{draftPts.pop();renderDraft()};$('finish').onclick=()=>{if(draftPts.length>=2)openEditor({id:Date.now(),name:'Līnija',type:'line',color:'#ff4b2b',height:0,points:draftPts.map(p=>({...p}))},true)};$('close').onclick=()=>{if(draftPts.length>=3){draftClosed=true;renderDraft();openEditor({id:Date.now(),name:'Laukums',type:'area',color:'#ff4b2b',height:0,points:draftPts.map(p=>({...p}))},true)}};$('reset').onclick=()=>{draftPts=[];draftClosed=false;clear(draftLayers);clearPreview();ui()};
 $('drawLine').onclick=()=>startDraw('line');$('drawArea').onclick=()=>startDraw('area');$('models').onclick=()=>location.href='yard-3d.html?v=16';$('edit').onclick=()=>{editing=!editing;activeId=null;$('edit').classList.toggle('active',editing);renderSaved();renderDraft();ui();toast(editing?'✎ Pieskaries jebkuram objektam':'Rediģēšana izslēgta')};$('save').onclick=saveEditor;$('cancel').onclick=()=>{$('modal').classList.remove('show');pending=null};$('deleteObject').onclick=deleteActive;$('pdf').onclick=()=>window.print();
 $('panelToggle').onclick=()=>{const h=$('bottom').classList.toggle('hidden');$('panelToggle').classList.toggle('panel-open',!h);$('panelToggle').textContent=h?'⌃':'⌄';setTimeout(()=>map.invalidateSize(),220)};$('follow').onclick=()=>{follow=true;$('follow').classList.add('active');if(pos){programmatic=true;map.setView([pos.lat,pos.lng],Math.max(19,map.getZoom()),{animate:false});setTimeout(()=>programmatic=false,100)}};$('boundaries').onclick=()=>{boundariesOn=!boundariesOn;$('boundaries').classList.toggle('active',boundariesOn);if(boundariesOn){cad.addTo(map);cad.bringToFront();cad.redraw()}else map.removeLayer(cad)};
 map.on('dragstart zoomstart',()=>{if(programmatic||drawMode)return;follow=false;$('follow').classList.remove('active')});map.on('click',e=>{if(!drawMode)return;drawPts.push({lat:e.latlng.lat,lng:e.latlng.lng});renderDraw()});map.on('moveend zoomend',()=>{if(boundariesOn&&cad&&map.hasLayer(cad))cad.redraw()});
 if(navigator.geolocation)navigator.geolocation.watchPosition(p=>{pos={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy};$('gpsText').textContent='± '+Math.round(pos.accuracy)+' m';$('dot').className='dot '+(pos.accuracy<=5?'good':pos.accuracy>15?'bad':'');const ll=[pos.lat,pos.lng];if(!gpsMarker)gpsMarker=L.marker(ll,{pane:'measure',icon:icon('gps'),interactive:false,zIndexOffset:1800}).addTo(map);else gpsMarker.setLatLng(ll);if(!accCircle)accCircle=L.circle(ll,{pane:'measure',radius:pos.accuracy,color:'#2f80ff',weight:2,fillColor:'#2f80ff',fillOpacity:.08,interactive:false}).addTo(map);else accCircle.setLatLng(ll).setRadius(pos.accuracy);if(follow){programmatic=true;map.setView(ll,Math.max(19,map.getZoom()),{animate:false});setTimeout(()=>programmatic=false,100)}updatePreview();ui()},e=>{$('dot').className='dot bad';$('gpsText').textContent=e.code===1?'GPS bloķēts':'GPS kļūda'},{enableHighAccuracy:true,maximumAge:0,timeout:20000});
 window.addEventListener('storage',renderSaved);window.addEventListener('yard-data-changed',renderSaved);setTimeout(()=>{map.invalidateSize();if(cad)cad.redraw()},250)}
init();
})();